/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jaspol.view;

import br.com.jaspol.dao.CalculadoraDao;
import br.com.jaspol.model.EditaEletro;
import br.com.jaspol.model.Eletro;
import br.com.jaspol.model.LoginResponse;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author antonio
 */
public class JListaEletro extends javax.swing.JFrame {
    
    private final CalculadoraDao dao;
    private final LoginResponse userResponse;
    private List<Eletro> elet;
    private int idx;

    /**
     * Creates new form JListaEletro
     */
    public JListaEletro(CalculadoraDao dao, LoginResponse userResponse ) {
        initComponents();
        this.dao = dao;
        this.setTitle("Eletronicos");
        this.userResponse = userResponse;
        preencherEletros(this.userResponse.getId().toString());
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    private void preencherEletros(String id){
        DefaultListModel m = new DefaultListModel();
        String retorno = this.dao.getEletro(id);
        if (retorno.contains("potencia")) {
            elet = new Gson().fromJson(this.dao.getEletro(id), new TypeToken<ArrayList<Eletro>>() {
            }.getType());
            if (!elet.isEmpty()) {
                for (Eletro eletro : elet) {
                    m.addElement(eletro.getName());
                }
                jListEletro.setModel(m);
            } else {
                jListEletro.setModel(m);
            }
        }else{
            JOptionPane.showMessageDialog(null, retorno);
            jListEletro.setModel(m);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListEletro = new javax.swing.JList<>();
        jTextName = new javax.swing.JTextField();
        jTextMarca = new javax.swing.JTextField();
        jTextPotencia = new javax.swing.JTextField();
        jTextTempo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jGastoDiaKW = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jGastoDiaReais = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jGastoMesKw = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jGastoMesReais = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonExcluirUser = new javax.swing.JButton();
        jButtonCep = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListEletro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListEletro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListEletroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListEletro);

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jLabel1.setText("NOME:");

        jLabel2.setText("MARCA:");

        jLabel3.setText("POTÊNCIA:");

        jLabel4.setText("TEMPO DE USO:");

        jLabel5.setText("GASTO POR DIA EM REAIS");

        jGastoDiaKW.setText("...");

        jLabel6.setText("GASTO POR DIA EM KW");

        jGastoDiaReais.setText("...");

        jLabel7.setText("GASTO POR MÊS EM KW");

        jGastoMesKw.setText("...");

        jLabel8.setText("GASTO POR MÊS EM REAIS");

        jGastoMesReais.setText("...");

        jButton1.setText("LIMPAR CAMPOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("CADASTRAR ");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("EDITAR");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonExcluirUser.setText("Excluir Usuário");
        jButtonExcluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirUserActionPerformed(evt);
            }
        });

        jButtonCep.setText("CEP");
        jButtonCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCepActionPerformed(evt);
            }
        });

        jLabel9.setText("BONUS: Informações Sobre seu CEP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButtonCep, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextName, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(jTextMarca)
                                    .addComponent(jTextPotencia)
                                    .addComponent(jTextTempo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jGastoMesReais, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jGastoMesKw, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jGastoDiaReais, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jGastoDiaKW, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(143, 143, 143))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 127, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jGastoDiaKW)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jGastoDiaReais)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jGastoMesKw)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jGastoMesReais))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonSair))
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluirUser)
                    .addComponent(jButtonCep))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jListEletroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListEletroMouseClicked
        this.idx = jListEletro.getSelectedIndex();
        if ( idx >= 0){
            Eletro eletroView = this.elet.get(idx);
            jTextName.setText(eletroView.getName());
            jTextMarca.setText(eletroView.getMarca());
            jTextPotencia.setText(eletroView.getPotencia().toString());
            int beginIdndex = eletroView.getTempoUso().toString().indexOf(".");
            int multiplica = Integer.parseInt(eletroView.getTempoUso().toString().substring(beginIdndex+1));
            if(multiplica == 0){
                jTextTempo.setText(eletroView.getTempoUso().toString().substring(0, beginIdndex).concat(":").concat("00"));
            }else{
                Double minuto;
                if (multiplica > 9) {
                    minuto = (new Double(multiplica) * 0.6);
                } else {
                    minuto = (new Double(multiplica) * 6);
                }
                jTextTempo.setText(eletroView.getTempoUso().toString().substring(0, beginIdndex).concat(":").concat(minuto.toString().format("%.0f", minuto)));
            }
            jGastoDiaKW.setText(eletroView.getGastoDiaWatts().toString());
            jGastoDiaReais.setText(eletroView.getGastoDiaReais().toString());
            jGastoMesKw.setText(eletroView.getGastoMesWatts().toString());
            jGastoMesReais.setText(eletroView.getGastoMesReais().toString());
        }
    }//GEN-LAST:event_jListEletroMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextName.setText("");
        jTextMarca.setText("");
        jTextPotencia.setText("");
        jTextTempo.setText("");
        jGastoDiaKW.setText("...");
        jGastoDiaReais.setText("...");
        jGastoMesKw.setText("...");
        jGastoMesReais.setText("...");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if(!jTextName.getText().isEmpty() && !jTextMarca.getText().isEmpty() 
                && !jTextPotencia.getText().isEmpty() && !jTextTempo.getText().isEmpty()){
            Eletro eletronico = this.elet.get(idx);
            JOptionPane.showMessageDialog(null, this.dao.deleteEletro(eletronico.getId().toString()));
            this.preencherEletros(this.userResponse.getId().toString());
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum Eletronico Selecionado!");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonExcluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirUserActionPerformed
         if(!(jListEletro.getModel().getSize() > 0)){
             JOptionPane.showMessageDialog(null,this.dao.deleteUser(this.userResponse.getId().toString()));
         }else{
             JOptionPane.showMessageDialog(null,"Delete os Eletronicos antes de excluir o usuário!" );
         }
    }//GEN-LAST:event_jButtonExcluirUserActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if (!jTextName.getText().isEmpty() && !jTextMarca.getText().isEmpty()
                && !jTextPotencia.getText().isEmpty() && !jTextTempo.getText().isEmpty()) {
            if (!jTextPotencia.getText().toLowerCase().contains("^[a-Z]")) {
                if (!(jTextPotencia.getText().contains(","))
                        && !(jTextPotencia.getText().contains("."))) {
                    if (!jTextTempo.getText().contains("^[a-Z]")) {
                        if (!(jTextTempo.getText().length() > 5)) {
                            Eletro eletronico = this.elet.get(idx);
                            EditaEletro editaEletro = new EditaEletro();
                            editaEletro.setId(eletronico.getId());
                            editaEletro.setName(jTextName.getText());
                            editaEletro.setMarca(jTextMarca.getText());
                            editaEletro.setPotencia(Integer.parseInt(jTextPotencia.getText()));
                            if (jTextTempo.getText().contains(".")) {
                                editaEletro.setTempoUso(Double.parseDouble(jTextTempo.getText()));
                            } else if (jTextTempo.getText().contains(":")) {
                                int beginIdndex = jTextTempo.getText().indexOf(":");
                                Double divide = Double.parseDouble(jTextTempo.getText().substring(beginIdndex + 1));
                                Double minuto = (divide / 60);
                                Double tempoUso = (Double.parseDouble(jTextTempo.getText().substring(0, beginIdndex)) + minuto);
                                editaEletro.setTempoUso(tempoUso);
                            } else {
                                editaEletro.setTempoUso(Double.parseDouble(jTextTempo.getText()));
                            }
                            editaEletro.setPessoaIdFk(this.userResponse.getId());
                            JOptionPane.showMessageDialog(null, this.dao.editaEletro(editaEletro));
                            this.preencherEletros(this.userResponse.getId().toString());
                        } else {
                            JOptionPane.showMessageDialog(null, "Formato inválido para horas!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Campo de tempo de uso não aceita letras!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Campo de potência não aceita letras ou simbolos!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Campo de potência não aceita letras ou simbolos!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum Eletronico Selecionado!");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        if (!jTextName.getText().isEmpty() && !jTextMarca.getText().isEmpty()
                && !jTextPotencia.getText().isEmpty() && !jTextTempo.getText().isEmpty()) {
            if (!(jTextPotencia.getText().contains("^[a-Z]")) && !(jTextPotencia.getText().contains(",")) && !(jTextPotencia.getText().contains("."))) {
                if (!jTextTempo.getText().contains("^[a-Z]")) {
                    if (!(jTextTempo.getText().length() > 5)) {
                        Eletro newEletro = new Eletro();
                        newEletro.setName(jTextName.getText());
                        newEletro.setMarca(jTextMarca.getText());
                        newEletro.setPotencia(Integer.parseInt(jTextPotencia.getText()));
                        if (jTextTempo.getText().contains(".")) {
                            newEletro.setTempoUso(Double.parseDouble(jTextTempo.getText()));
                        } else if (jTextTempo.getText().contains(":")) {
                            int beginIdndex = jTextTempo.getText().indexOf(":");
                            Double divide = Double.parseDouble(jTextTempo.getText().substring(beginIdndex+1,beginIdndex+3));
                            Double minuto = (divide / 60);
                            Double tempoUso =(Double.parseDouble(jTextTempo.getText().substring(0, beginIdndex))+minuto);
                            newEletro.setTempoUso(tempoUso);
                        } else {
                            newEletro.setTempoUso(Double.parseDouble(jTextTempo.getText()));
                        }
                        newEletro.setPessoaIdFk(this.userResponse.getId());
                        JOptionPane.showMessageDialog(null, this.dao.newEletro(newEletro));
                        this.preencherEletros(this.userResponse.getId().toString());
                    } else {
                        JOptionPane.showMessageDialog(null, "Formato inválido para horas!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Campo de tempo de uso não aceita letras!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Campo de potência não aceita letras ou simbolos!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCepActionPerformed
        JCep cep = new JCep(this.dao);
        cep.setVisible(true);
        cep.setTitle("Informações sobre seu CEP.");
    }//GEN-LAST:event_jButtonCepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JListaEletro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JListaEletro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JListaEletro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JListaEletro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new JListaEletro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCep;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirUser;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jGastoDiaKW;
    private javax.swing.JLabel jGastoDiaReais;
    private javax.swing.JLabel jGastoMesKw;
    private javax.swing.JLabel jGastoMesReais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListEletro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextMarca;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPotencia;
    private javax.swing.JTextField jTextTempo;
    // End of variables declaration//GEN-END:variables
}
